#' A function that takes an output file from the Uniprot command line tool
#' 
#'This function takes an output file from the command line tool built to access uniprot. This tool takes a file generated by the unip function. You must request the data be returned as gff format. Sometimes there is a header
#'that must be removed before the gff data. This tool can be found here https://github.com/jdrudolph/uniprot.
#'It will return this as an R dataframe. 
#' 
#' 
#' @param ptmfile Output file from uniprot command line tool
#' @keywords PTMS, Uniprot 
#' @export
#' @examples
#' Command line Usage:
#' uniprot retrieve -f gff uniprot.txt output.txt 
#' 
#' ptmdf <- readPTM(ptmfile = 'output.txt')

readPTM <- function(ptmfile = 'output.txt'){
  
  ptmdf <- read.gff(ptmfile)
  return(ptmdf)
  
}